import 'tailwindcss/tailwind.css';
import SidebarLayout from '../components/sidebar-layout';

export const metadata = {
  title: 'Welcome to e-shop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SidebarLayout>{children}</SidebarLayout>
        <div className="bg-gray-50"> <span className="block">Ready to dive in?</span></div>
        <div className="bg-indigo-500 p-2 font-mono">Hello!</div>
      </body>
    </html>
  );
}
